id: P004272
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG22129
  title: རང་རིགས་ཕུ་ནུ་སྤྲོ་སྐྱིད་འཕེལ་བའི་གཏམ་ཚོགས་ལས་བྱེ་བྲག་གླུ་གཞས་སྣ་ཚོགས།
  author: ''
  volumes:
    c8fbdea65a5b47e29d8c51cb1a8dd700:
      image_group_id: I1KG22214
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
